<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IM-LP-2521" failures="1" tests="3" name="Events.xml" time="72.265" errors="0" timestamp="2024-01-01T22:04:14 IST">
  <testcase classname="org.aia.testcases.ces.SampleTest" name="Test1" time="60.056"/>
  <testcase classname="org.aia.testcases.ces.SampleTest" name="Test2" time="6.009">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.aia.testcases.ces.SampleTest.Test2(SampleTest.java:26)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="org.aia.testcases.ces.SampleTest" name="Test3" time="6.01"/>
</testsuite> <!-- Events.xml -->
